version: '3'
services:
  nginx:
    restart: on-failure
    image: nginx:stable-alpine
    container_name: shippii_api_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - shippii-network
  postgres:
    image: postgres
    container_name: shippii_api_postgres
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: shippii_api
      POSTGRES_USER: shippii_api
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    ports:
      - "5432:54320"
    volumes:
      - ~/docker-shippii-data/postgres-data:/var/lib/postgresql/data
    networks:
      - shippii-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shippii_api_php
    volumes:
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - shippii-network
  redis:
    container_name: shippii_api_redis
    image: redis:latest
    depends_on:
      - nginx
      - php
      - postgres
    ports:
      - "63820:63791"
#Shippii Networks
networks:
  shippii-network:
    driver: bridge
